@startuml RescateDePatitas

class Contacto{
  apellido
  nombre
  teléfono
  email
}

class Mascota{
  clase
  nombre
  apodo
  edad
  sexo
  descripcionFísica
  fotos[]
  características[]
}

enum Clase{
  GATO
  PERRO
}

class Documento{
  tipo
  numero
}

enum TipoDeDocumento{
  DNI
  LC /' Libreta Cívica '/
  LE /' Libreta de Enrolamiento '/
  CI /' Cédula de Identidad '/
  PASAPORTE
}

class Rescate{
  rescatista
  mascota
  fotos[]
  descripcion
  ubicacion
  fecha
}

class Coordenadas{
  latitud
  longitud
}

class Usuario{
  username
  password
}

class Administrador{
  agregarUnaCaracterística()
  eliminarUnaCaracterística()

}

class Dueño{
  mascotasRegistradas[]
  registrarUnaMascota()
  esMiMascota()
}

abstract class Repositorio {
  repositorio
  registrar()
  borrar()
  buscar()
  filtrar()
  cantidadDeRegistros()
  contar()
  existe()
  vaciar()
  
}

class RepositorioDueños{
  duenioDe()
}


class RepositorioMascotas{
  obtenerDueñoDe()
}


class RepositorioRescates{
  últimasMascotasEncontradas()
  confirmarMascotaEncontrada()
}

class Característica{
  título
  opciones[]
  agregarOpcion()
  tieneEstaOpcion()
}

class RepositorioCaracteristicas{
  existeCaracteristica()
  borrarCaracteristica()
  obtenerCaracteristica()
  opcionesDe()
}

class PasswordValidator{
  validatePassword()
}

class Rescatista{
  direccion
  registrarRescate()
}

class DatosPersona{
  apellido
  nombre
  fechaDeNacimiento
  documento
  contacto
}


class RepositorioAdministradores{

}

Dueño -u-> DatosPersona
Rescatista -u-> DatosPersona
DatosPersona -r-> Documento
DatosPersona -l-> Contacto
Rescate -u-> Rescatista
Usuario -l-> PasswordValidator
Dueño -u-|> Usuario
Rescate -d-> Mascota
Documento -r-> TipoDeDocumento
Mascota -l-> Clase
Dueño -d->"*" Mascota
Administrador -u-|> Usuario
Rescate -> Coordenadas
RepositorioMascotas -u-> "*" Mascota
RepositorioRescates -u-> "*" Rescate
RepositorioDueños -u-> "*" Dueño
RepositorioAdministradores -u-> "*" Administrador
RepositorioCaracteristicas ->"*" Característica
RepositorioMascotas -d-|> Repositorio
RepositorioRescates -d-|> Repositorio
RepositorioCaracteristicas -l-|> Repositorio
RepositorioAdministradores -d--|> Repositorio
RepositorioDueños -d-|> Repositorio

@enduml
