@startuml RescateDePatitas

class Persona{
  apellido
  nombre
  fechaDeNacimiento
  tipoDeDocumento
  númeroDeDocumento
  contacto

}

class Contacto{
  apellido
  nombre
  teléfono
  email
}

class Mascota{
  clase
  nombre
  apodo
  edad
  sexo
  descripcionFísica
  fotos[]
  características[]
}

enum Clase{
  GATO
  PERRO
}


enum TipoDeDocumento{
  DNI
  LC /' Libreta Cívica '/
  LE /' Libreta de Enrolamiento '/
  CI /' Cédula de Identidad '/
  PASAPORTE
}

class Rescate{
  rescatista
  mascota
  fotos[]
  descripcion
  ubicacion
  fecha
}

class Coordenadas{
  latitud
  longitud
}

class Usuario{
  username
  password
}

class Administrador{
  usuario
  agregarUnaCaracterística()
  eliminarUnaCaracterística()

}

class Dueño{
  usuario
  mascotasRegistradas[]
  registrarUnaMascota()
  esMiMascota()
}

class RepositorioUsuarios{
  dueñosRegistrados[]
  administradoresRegistrados[]
  registrarAdminsitrador()
  registrarDueño()
}

class RepositorioMascotas{
  mascotasRegistradas[]
  registrarMascota()
  obtenerDueñoDe()
}

class RepositorioRescates{
  mascotasEncontradas[]
  últimasMascotasEncontradas()
  confirmarMascotaEncontrada()
  registrarRescate()
}

class Característica{
  título
  opciones[]
  agregarOpcion()
  tieneEstaOpcion()
}

class RepositorioCaracteristicas{
  características[]
  agregarCaracteristica()
  borrarCaracteristica()
  obtenerCaracteristica()
  opcionesDe()
}

class PasswordValidator{
  validatePassword()
}

Rescate -u-> Persona
Usuario -> PasswordValidator
Dueño -u-|> Usuario
Rescate -d-> Mascota
RepositorioMascotas -l-> "*" Mascota
RepositorioRescates -u-> "*" Rescate
RepositorioUsuarios -l-> "*" Administrador
RepositorioUsuarios -r-> "*" Dueño
Persona -> TipoDeDocumento
Dueño -u-> Persona
Persona -l-> Contacto
Mascota -l-> Clase
Dueño -d->"*" Mascota
Administrador -u-|> Usuario
Rescate -> Coordenadas
RepositorioCaracteristicas ->"*" Característica
Dueño ..>"usa" RepositorioCaracteristicas
Administrador ..>"modifica" RepositorioCaracteristicas

@enduml
